# Wazuh App Copyright (C) 2020 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: ${REPO}rbkmoney/wazuh
    restart: always
    networks:
      ipv6_net:
    volumes:
      - "./configs/wazuh/etc/ossec.conf:/var/ossec/etc/ossec.conf:ro"
      - "./configs/wazuh/api/configuration/config.js:/var/ossec/api/configuration/config.js:ro"
      - "./configs/pki/:/var/ossec/pki/:ro"
      - "./logs/:/var/ossec/data/logs/:rw"
      - "./configs/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro"
    environment:
      - "API_USER=${API_USER}"
      - "API_PASS=${API_PASS}"
      - "AGENT_REG_PASS=${AGENT_REG_PASS}"
      - "API_GENERATE_CERTS=false"
    # ports:
    #   - "1514:1514/udp"
    #   - "1515:1515"
    #   - "514:514/udp"
    #   - "55000:55000"

  elasticsearch:
    image: ${REPO}rbkmoney/wazuh-elasticsearch
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    networks:
      ipv6_net:
  
  kibana:
    image: ${REPO}rbkmoney/wazuh-kibana
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    networks:
      ipv6_net:
    ports:
      - 5601:5601
    environment:
      - "WAZUH_API_URL=https://wazuh"
      - "API_USER=${API_USER}"
      - "API_PASS=${API_PASS}"
      - "WAZUH_SKIP_TESTS=true"

  wazuh-agent:
    image: ${REPO}rbkmoney/wazuh-agent
    hostname: wazuh_agent
    restart: always
    depends_on:
      - wazuh
    environment:
      - WAZUH_MANAGER=wazuh
      - "AGENT_REG_PASS=${AGENT_REG_PASS}"
    networks:
      ipv6_net:

networks:
  ipv6_net:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fcc7:b4f4:59f2:9971:22cb::/80"
